/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class one_papachi_dokany4j_Dokany4j */

#ifndef _Included_one_papachi_dokany4j_Dokany4j
#define _Included_one_papachi_dokany4j_Dokany4j
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     one_papachi_dokany4j_Dokany4j
 * Method:    mount
 * Signature: (IZILjava/lang/String;Ljava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_one_papachi_dokany4j_Dokany4j_mount
        (JNIEnv *, jobject, jint, jboolean, jint, jstring, jstring, jint, jint, jint);

/*
 * Class:     one_papachi_dokany4j_Dokany4j
 * Method:    unmount
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_one_papachi_dokany4j_Dokany4j_unmount
        (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
